### ISSUE TITLE
Error when deploying frontend

### ISSUE THREAD

**Issue by richiesgr** [whs-dot-hk/kubernetes-nifi-refined#3]
Hi 
I'm trying to apply your config to deploy nifi on EKS (AWS) I've succeed so far to deploy nifi but a problem occurs when deploying frontend
the pod crash because NginX can't find host nifi defined in frontend.conf 
So I get this error 
 2019/05/07 09:46:30 [emerg] 1#1: host not found in upstream "nifi" in /etc/nginx/conf.d/frontend.conf:5
nginx: [emerg] host not found in upstream "nifi" in /etc/nginx/conf.d/frontend.conf:5

could you help me ?
Thanks

**Comment by jkogut** [comment]
You have to change in `/nifi-frontend/frontend.conf`:

http://nifi-headless:8080

**Comment by whs-dot-hk** [comment]
@richiesgr Hi, is it the cluster mode?

Which part of the guide are you following?

**Comment by richiesgr** [comment]
Hi
Yes I've followed the cluster mode tutorial and I try to deploy on EKS 1.11 on AWS.
but I think it could be related to this problem [CoreDNS support for ExternalName services is broken in EKS 1.11](https://github.com/aws/containers-roadmap/issues/129) as you use ExternalName to resolve nifi host name for NginX
What do you think ?
Thanks

**Comment by richiesgr** [comment]
Hi
Update may be worth to add this to your documentation.
The core-dns 1.1.3 used by default on EKS 1.11 is broken for externalName service.
it's not enough to  update EKS to 1.12 you must update the core-dns to version 1.2.2
After upgrade all is working as expected 
Thanks
